### ISSUE TITLE
Remove .git directory from npm package.

### ISSUE THREAD

**Issue by azzadrood** [watadarkstar/react-native-typing-animation#2]
Hello,

I have this error when i try to install another package to my project after i have installed your package.

![Screenshot 2019-03-28 at 14 16 26](https://user-images.githubusercontent.com/9199523/55157176-76030680-5164-11e9-84d1-d074c6a81e87.jpg)

So i have to enter node-modules/react-native-typing-animation and remove .git directory.

![Screenshot 2019-03-28 at 14 15 45](https://user-images.githubusercontent.com/9199523/55157175-756a7000-5164-11e9-843c-d6a13411f90f.jpg)

Can you remove .git folder from npm package?

Thank you in advanced.

Btw very nice animation!

**Comment by watadarkstar** [comment]
@azzadrood Can you update to 0.1.7 it might be fixed, I added the `.git` to the `.gitignore` but im not sure if this will actually work

**Comment by azzadrood** [comment]
Hello i have tested right now and I can confirm that it works well. 
Thanks!

**Comment by watadarkstar** [comment]
Sounds good glad it worked @azzadrood
